### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by lorenzcarva** [KaylaDunn/CEN3031Project#2]
- [x] Develop a project description and a project name
- [x] Create a Github repository for the project. In the root README, list the following:
     - [x] Project name
     - [x] Project description
     - [x] Members
- [ ] Submit the link to your repository (one submission per group)
- [x] Project Description: Does your GitHub README have a project description? (25 pts)
- [x] All Members are Collaborators (25 pts)
     - [x] Add all members to GitHub repository
     - [x] TA's, check the Insights > Collaborators for members of the group.
- [x] GitHub Link (50 pts)
     - [x] Link to Github project works and repository is public.

**Comment by lorenzcarva** [comment]
Just checked if the link works on a Guest user and it's all good so I'll just submit it now if everyone is okay with that.

**Comment by lorenzcarva** [comment]
Idea for a feature to add to our project: if a user likes a certain post that is linked to a location, have a recommendations tab/window that'll provide travel information to that place. For example, if I like a post about Paris, something will show up somewhere saying "Airplane tickets to Paris are currently $100" with a link to buy it if the user wants to. This way, we can probably incorporate other websites into ours and theoretically make some kind of advertising revenue if this was a real thing. What do you guys think?

**Comment by rrohans** [comment]
> Idea for a feature to add to our project: if a user likes a certain post that is linked to a location, have a recommendations tab/window that'll provide travel information to that place. For example, if I like a post about Paris, something will show up somewhere saying "Airplane tickets to Paris are currently $100" with a link to buy it if the user wants to. This way, we can probably incorporate other websites into ours and theoretically make some kind of advertising revenue if this was a real thing. What do you guys think?

I like the ad idea, sounds cool!

**Comment by tmcooney** [comment]
> Idea for a feature to add to our project: if a user likes a certain post that is linked to a location, have a recommendations tab/window that'll provide travel information to that place. For example, if I like a post about Paris, something will show up somewhere saying "Airplane tickets to Paris are currently $100" with a link to buy it if the user wants to. This way, we can probably incorporate other websites into ours and theoretically make some kind of advertising revenue if this was a real thing. What do you guys think?

sounds like a great idea

**Comment by lorenzcarva** [comment]
Submitted Sprint 0. We can also add to the description/name until Wednesday if anyone has more ideas!
