### ISSUE TITLE
Implementing User Stories

### ISSUE THREAD

**Issue by lorenzcarva** [KaylaDunn/CEN3031Project#5]
From lecture on 1/25/23, we are being asked to put down "user stories" into our GitHub as issues. We were shown [this article](https://www.atlassian.com/agile/project-management/user-stories).

[On here](https://github.com/solid/user-stories) they're defined as: "short descriptions of a need written from the perspective of a user."

General format/process we can follow is to 
1. Open an issue
2. The user story should fit as the title: "As a [type of user], I want [some goal] so that [some reason]."
3. Additional details in the description
4. And can use the space in the comments to further discuss the feature

Also make sure before opening a new issue that there's not already an equivalent one in the list of issues.

These are mandatory or we get points off.

**Comment by lorenzcarva** [comment]
Also I'm understanding that we can link code files to issues so that we can be really organized as to which code is meant to solve which problem/feature.

**Comment by lorenzcarva** [comment]
Make sure to consider:
1. Definition of "done"
2. Outline subtasks
3. User personas
4. Ordered steps
5. Listen to feedback
6. Time (stories should be completable in one sprint)

**Comment by lorenzcarva** [comment]
I've added several issues to Sprint 4, but more will be added tomorrow. Next, we want to narrow down the issues into checklists/more specific tasks in order to complete each one.

**Comment by KaylaDunn** [comment]
All issues planned to get done before Sprint 4 ends are included. Optional issues talked about in a zoom meeting will possibly be added once the main issues presented are solved.
