### ISSUE TITLE
As a logged-in user on the webpage, I want to upload a post containing an image and description, so that it can be saved in the server.

### ISSUE THREAD

**Issue by lorenzcarva** [KaylaDunn/CEN3031Project#7]
Logged in users.

**Comment by rrohans** [comment]
The ability to upload images to the server is now possible via the API.

**Comment by lorenzcarva** [comment]
Error with creating a post, authentication related.

**Comment by lorenzcarva** [comment]
Resolved authentication/post/put errors.
